mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'lendborrow.views.index', name='index'),
    url(r'^register/$', 'lendborrow.views.register', name='register'),
    url(r'^login/$', 'lendborrow.views.user_login', name='login'),
    url(r'^borrow/$', 'lendborrow.views.borrow', name='borrow_transactions'),
    url(r'^borrow/edit', 'lendborrow.views.borrow_edit', name='borrow_transactions'),
    url(r'^returned/','lendborrow.views.returned', name='returned'),
    url(r'^reports/', 'lendborrow.views.display_reports', name='reports'),
    url(r'^selected/', 'lendborrow.views.record_selected', name='record_selected'),
)

lendborrow/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from datetime import datetime

class UserProfile(models.Model):
    #extend the auth.User
    user = models.OneToOneField(User)
    initials = models.CharField(max_length=2, blank=True)
    cell_phone = models.CharField(max_length=25)
    location = models.CharField(max_length=50)

    borrower_score = models.IntegerField(default=50)
    lender_score = models.IntegerField(default=50)
    items_lent = models.IntegerField(default=0)
    items_lent_forgiven = models.IntegerField(default=0)
    items_lent_returned = models.IntegerField(default=0)

    items_borrowed = models.IntegerField(default=0)
    items_borrowed_forgiven = models.IntegerField(default=0)
    items_returned = models.IntegerField(default=0)

    def __unicode__(self):
        return '{} {} ({})'.format(self.user.first_name, self.user.last_name, self.location)

    def save_initials(self):
        self.initials = '{}{}'.format(self.user.first_name[0], self.user.last_name[0])
        self.save()

class BorrowTransaction(models.Model):
    #one borrowing transaction can have several items lent to the same person
    borrowed_date = models.DateTimeField(default=timezone.now())
    lender = models.ForeignKey('auth.User', related_name='lender')
    borrower = models.ForeignKey('auth.User', related_name='borrower',
                                 error_messages={'required': 'please choose a borrower', 'null': 'NULL11!'})

    def new_borrow_transaction(self):
        Borrowed_Item.objects.create(borrow_transaction=self)

    def __unicode__(self):
        return '{0} lent to {1}: {2:%Y}_{2:%m}_{2:%d}'.format(self.lender, self.borrower, self.borrowed_date)

class Borrowed_Item(models.Model):
    # a borrow transaction can have several items lent (each as a separate line item)
    ITEM_CATEGORIES = (
        ('AP', 'Apparel - clothing, shoes, accessories'),
        ('JW', 'Jewelry'),
        ('BK', 'Book'),
        ('EL', 'Electronics'),
        ('CD', 'CDs, DVDs'),
        ('PG', 'Party Goods'),
        ('TL', 'Tools'),
        ('OT', 'other')
    )

    ITEM_CONDITIONS_CHOICES = (
        ('NW', 'New'),
        ('LN', 'Used, Like New'),
        ('VG', 'Used, Very Good'),
        ('GD', 'Used, Good'),
        ('FR', 'Used, Fair'),
        ('PR', 'Used, Poor'),
    )  #TODO is there a way to give each choice a weight or rating number / add another field?
    #  to be used for comparing borrowed condition with returned condition.

    SEND_REMINDERS_TO = (
        ('Email', 'Email'),
        ('Text', 'Text'),
        ('None', 'None'),
        ('Both', 'Both')
    )

    BORROWED_STATUS = (
        ('All', 'All Status'),
        ('Open', 'Open: Still Borrowed'),
        ('Returned', 'Returned'),
        ('Forgiven', "Forgiven: Don't expect to receive it back"),
        ('Cancelled', 'Cancelled: Was never really lent after all')
    )

    borrow_transaction = models.ForeignKey(BorrowTransaction, null=True, blank=True)
    item_category = models.CharField(max_length=2,
                                choices=ITEM_CATEGORIES)
    item_short_desc = models.CharField(max_length=255,)
    item_detail_desc = models.TextField(blank=True,)
    expected_return_date = models.DateField(null=True, blank=True)
    borrowed_condition = models.CharField(max_length=2,
                                          choices=ITEM_CONDITIONS_CHOICES)
    borrowed_comment = models.TextField(blank=True,)
    send_borrower_reminder = models.CharField(max_length=5,
                                          choices=SEND_REMINDERS_TO)
    borrowed_status = models.CharField(max_length=9,
                                       blank=True, null=True,
                                       default='Open')

    returned_date = models.DateField(blank=True, null=True)
    returned_condition = models.CharField(max_length=2,
                                          choices=ITEM_CONDITIONS_CHOICES,
                                          blank=True, null=True)
    returned_comment = models.TextField(blank=True)

    def __unicode__(self):
        return '{}'.format(self.item_short_desc)

    def item_is_borrowed(self):
        #for each item borrowed, these methods happen
        self.borrowed_status = 'Open'

        lender_profile = UserProfile.objects.get(user=self.borrow_transaction.lender)
        lender_profile.items_lent +=1
        lender_profile.save()

        borrower_profile = UserProfile.objects.get(user=self.borrow_transaction.borrower)
        borrower_profile.items_borrowed +=1
        borrower_profile.save()

    def borrow_is_cancelled(self):
        borrower_profile = UserProfile.objects.get(user=self.borrow_transaction.borrower)
        borrower_profile.items_borrowed -=1
        borrower_profile.save()

        lender_profile = UserProfile.objects.get(user=self.borrow_transaction.lender)
        lender_profile.items_lent -=1
        lender_profile.save()


    def borrow_is_forgiven(self):
        borrower_profile = UserProfile.objects.get(user=self.borrow_transaction.borrower)
        borrower_profile.items_borrowed_forgiven +=1
        borrower_profile.save()

        lender_profile = UserProfile.objects.get(user=self.borrow_transaction.lender)
        lender_profile.items_lent_forgiven +=1
        lender_profile.save()


    def item_is_returned(self):
        #after item is returned,
        self.borrowed_status = 'Returned'
        self.returned_date = timezone.now()
        self.save()

        borrower_profile = UserProfile.objects.get(user=self.borrow_transaction.borrower)
        borrower_profile.items_returned +=1
        borrower_profile.save()

        lender_profile = UserProfile.objects.get(user=self.borrow_transaction.lender)
        lender_profile.items_lent_returned +=1
        lender_profile.save()

        date_diff = ((self.returned_date.date() - self.expected_return_date).days)
        if date_diff < 0:
            print 'returned {} days EARLY. thank you!'.format(abs(date_diff))
        elif date_diff == 0:
            print 'returned on time. thank you!'
        elif date_diff >0:
            print 'returned {} days LATE. please be on time next time!'.format(abs(date_diff))



        #3. compare 'borrowed_condition' and 'returned_condition'
        #     if ==, borrower_score +=3
        #     if <, borrower_score -= (3* levels less than borrowed_condition)

lendborrow/views.py
from django.shortcuts import *
from django.contrib.auth import authenticate, login

from django.contrib.auth.models import User
from django.template import RequestContext
from django.views.generic import View, ListView, CreateView,  UpdateView, DeleteView, DetailView

from datetime import date, datetime, timedelta

from forms import UserProfileForm, UserForm, BorrowForm, BorrowedItemsForm, RequestReportsForm, ReturnItemForm
from models import Borrowed_Item, BorrowTransaction, UserProfile

def user_login(request):
    #login
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'lendborrow/login.html', {})


def index(request):
    template_to_use = 'lendborrow/home.html'
    context = {}

    if request.method == 'POST':
        if 'New User' in request.POST['submitted']:
            context={'user_form': UserForm(),
                     'profile_form': UserProfileForm(),
                     'registered': False,
                     'mode': request.POST['submitted']}
            template = 'lendborrow/register.html'

        elif 'Edit User' in request.POST['submitted']:
            context={'logged_in_as': request.user,
                     'user_form': UserForm(),
                     'profile_form': UserProfileForm(),
                     'mode': request.POST['submitted']},
            template = 'lendborrow/register.html'

        elif 'New Borrow' in request.POST['submitted']:
            context={'logged_in_as': request.user,
                     'borrow_form': BorrowForm(),
                     'borrowed_items_form': BorrowedItemsForm(),
                     'mode': request.POST['submitted']}
            template = 'forms/borrow.html'

        elif 'Edit Borrow' in request.POST['submitted'] or 'Return Item' in request.POST['submitted']:
            all_open_borroweds = Borrowed_Item.objects.filter(borrow_transaction__lender=request.user)\
                                                    .filter(borrowed_status='Open')
            context={'logged_in_as': request.user,
                     'borroweds': all_open_borroweds,
                      'mode': request.POST['submitted']}
            template = 'forms/select_record.html'

        elif 'Request Report' in request.POST['submitted']:
            context = {'logged_in_as': request.user,
                       'form': RequestReportsForm}
            template = 'forms/request_report.html'

    else:
        if request.user:
            context = {'logged_in_as': request.user}
        template = 'lendborrow/home.html'

    return render(request, template, context)

def record_selected(request):
    all_open_borroweds = Borrowed_Item.objects.filter(borrow_transaction__lender=request.user)\
                                                    .filter(borrowed_status='Open')

    if "item to edit" in request.POST['submitted']:
        if not request.POST['item_id'].isdigit() or \
            int(request.POST['item_id']) not in all_open_borroweds.values_list('id', flat=True):

            error_message = 'You selected {}. That item is not available to be editted. ' \
                            'Please select an ID from the list.'.format(request.POST['item_id'])
            form = BorrowedItemsForm(request.POST)
            context = {'logged_in_as': request.user,
                       'form': form,
                       'mode': 'Edit Borrow',
                       'borroweds': all_open_borroweds,
                       'error_message': error_message}
            template = 'forms/select_record.html'
        else:
            to_edit = Borrowed_Item.objects.get(id=request.POST['item_id'])
            form = BorrowedItemsForm(instance=to_edit)
            context = {'logged_in_as': request.user,
                            'form': form,
                            'borrowed': to_edit }  #is this needed if the form is filled with the instance?
            template = 'forms/edit_borrowed.html'


    elif "item to return" in request.POST['submitted']:
         if not request.POST['item_id'].isdigit() or \
            int(request.POST['item_id']) not in all_open_borroweds.values_list('id', flat=True):

            error_message = 'You selected {}. That item is not available to be returned. ' \
                            'Please select an ID from the list.'.format(request.POST['item_id'])
            form = ReturnItemForm(request.POST)
            context = {'logged_in_as': request.user,
                       'form': form,
                       'mode': 'Return Item',
                       'borroweds': all_open_borroweds,
                       'error_message': error_message}
            template = 'forms/select_record.html'
            print Borrowed_Item.BORROWED_STATUS

         else:
            to_return = Borrowed_Item.objects.get(id=request.POST['item_id'])
            form = ReturnItemForm(instance=to_return)
            context = {'logged_in_as': request.user,
                        'form': form,
                        'to_return': to_return} #is this needed if the form is filled with the instance?
            template = 'forms/record_item_returned.html'

    return render(request, template, context)


def display_reports(request):
    form = RequestReportsForm(data=request.POST)
    if form.is_valid():
        if request.POST['report']=='lent report':
            borroweds = Borrowed_Item.objects.filter(borrow_transaction__lender=request.user)
            mode = 'lent'
            if request.POST['from_to']:
                borroweds = borroweds.filter(borrow_transaction__borrower=request.POST['from_to'])


        elif request.POST['report']=='borrowed report':
            borroweds = Borrowed_Item.objects.filter(borrow_transaction__borrower=request.user)
            mode = 'borrowed'
            if request.POST['from_to']:
                borroweds = borroweds.filter(borrow_transaction__lender=request.POST['from_to'])

        if request.POST['status']!='All':
            borroweds = borroweds.filter(borrowed_status=request.POST['status'])

        if request.POST['start_date'] and request.POST['end_date']:
            borroweds = borroweds.filter(borrow_transaction__borrowed_date__range=(start_date, end_date))

        return render(request, 'reports/report.html', {'logged_in_as': request.user,
                                                  'borroweds': borroweds,
                                                  'mode': mode})
    return render(request, 'forms/request_report.html',{'logged_in_as': request.user,
                                                        'form': RequestReportsForm(request.POST)})



def register(request):
    registered = False

    if request.method =='POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.save_initials()

            registered = True

        else:
            print user_form.errors, profile_form.errors

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'lendborrow/register.html',
            {'user_form': user_form,
             'profile_form': profile_form,
             'registered': registered},
            )


def borrow(request):
    if request.method == 'POST':
        form = BorrowForm(request.POST)


        if form.is_valid():

            borrowed_transaction = form.save(commit=False)
            borrowed_transaction.lender = request.user
            borrowed_transaction.save()

            form = BorrowedItemsForm(request.POST)
            if form.is_valid():
                print 'llll'
                borrowed_item = form.save(commit=False)
                borrow_trans_id = BorrowTransaction.objects.get(id=borrowed_transaction.id)
                borrowed_item.borrow_transaction = borrow_trans_id
                borrowed_item.item_is_borrowed()
                borrowed_item.save()
                return redirect('/')
            else:
                 context={'borrow_form': BorrowForm(request.POST),
                 'borrowed_items_form': BorrowedItemsForm(request.POST),
                 'mode': 'new borrow',
                 'lender': request.user,}
                 return render(request, 'forms/borrow.html', context)
                 print '1'
        else:
            context={'borrow_form': BorrowForm(request.POST),
                     'borrowed_items_form': BorrowedItemsForm(request.POST),
                 'mode': 'new borrow',
                 'lender': request.user}
            print '2'
            return render(request, 'forms/borrow.html', context)




    context={'borrow_form': BorrowForm(),
                 'borrowed_items_form': BorrowedItemsForm(),
                 'mode': 'new borrow',
                 'lender': request.user}
    print '3'
    return render(request, 'forms/borrow.html', context)

def borrow_edit(request):
    if request.method == 'POST':
        form = BorrowedItemsForm(request.POST)
        if form.is_valid():
            editted_item = Borrowed_Item.objects.get(id=request.POST['item_id'])
            editted_item.item_category = request.POST['item_category']
            editted_item.item_short_desc = request.POST['item_short_desc']

lendborrow/templates/forms/borrow.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% extends 'lendborrow/base.html' %}

{% block content %}
        New Borrow Transaction

    <form action = "/borrow/" method="POST">
        {% csrf_token %}

        <b>Borrower</b>{{borrow_form.borrower}}<br><b> {{ error_message }}</b><br>
        <hr>
        Item borrowed:<br>
        Category: {{borrowed_items_form.item_category}}
        Short description: {{borrowed_items_form.item_short_desc}}
        Detailed description: {{borrowed_items_form.item_detail_desc}}<br>
        Borrowed condition: {{borrowed_items_form.borrowed_condition}}
        Comment: {{borrowed_items_form.borrowed_comment}}<br>
        Expected return date: {{borrowed_items_form.expected_return_date}}
        Send borrower a reminder? {{borrowed_items_form.send_borrower_reminder}}<br>

        <input type="hidden" name="mode" value="new">
        <input type="submit" name="submit" value="Save" >

    </form>
{% endblock %}
</body>
</html>

lendborrow/templates/forms/edit_borrowed.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% extends 'lendborrow/base.html' %}
{% block content %}
    <h1>Edit Borrow</h1>
    <form action = "/borrow/edit/" method="POST">
        {% csrf_token %}

        <b>Borrower: </b>{{borrowed.borrow_transaction.borrower}} ( {{borrowed.id}} )
        <hr>
        Item borrowed:<br>
        Category: {{form.item_category}}
        Short description: {{form.item_short_desc}}
        Detailed description: {{form.item_detail_desc}}<br>
        Borrowed condition: {{form.borrowed_condition}}
        Borrowed Status: {{form.borrowed_status}}
        Comment: {{form.borrowed_comment}}<br>
        Expected return date: {{form.expected_return_date}}
        Send borrower a reminder? {{form.send_borrower_reminder}}<br>

        <input type="hidden" name="mode" value="edit">
        <input type="hidden" name="item_id" value={{borrowed.id}}>
        <input type="submit" name="submit" value="Save" >

    </form>
{% endblock %}
</body>
</html>

lendborrow/templates/forms/record_item_returned.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% extends 'lendborrow/base.html' %}
{% block content %}
<style>
    table, th, td {
        border: 1px solid black;
        font size="2";
        align="left";
    }
</style>
<h1> Returning Item</h1>
{{lender}}<br>
{{mode}}<br>



                <style>
table, th, td {
    border: 1px solid black;
    font size="2";
    align="left";
}
</style>


    <table>

            <col width="20">
            <col width="130">
            <col width="130">
            <col width="100">
            <col width="500">
            <col width="100">
            <col width="150">



            <th>
                Borrower
            </th>
            <th>
                Borrowed Date
            </th>
            <th>
                Category
            </th>
            <th>
                Description
            </th>
            <th>
                Condition
            </th>

            <th>
                Status
            </th>
            <th>
                Expected return date
            </th>


        <tr>

            <td>
                {{to_return.borrow_transaction.borrower}}
            </td>
            <td>
                {{to_return.borrow_transaction.borrowed_date|date:"m\/d\/Y"}}
            </td>
            <td>
                {{to_return.get_item_category_display}}
            </td>
            <td>
                {{to_return.item_short_desc}}
            </td>
            <td>
                {{to_return.get_borrowed_condition_display}}
            </td>
            <td>
                {{to_return.borrowed_status}}
            </td>
            <td>
                {{to_return.expected_return_date|date:"m\/d\/Y"}}
            </td>
        </tr>


    </table>
            <form action="/returned/" method="post">{% csrf_token %}
                <input type="hidden" name="item_id" value={{to_return.id}}>
                condition: {{form.returned_condition}}
                comment: {{form.returned_comment}}
                <input type="submit">
            </form>
{% endblock %}
</body>
</html>

lendborrow/templates/forms/request_report.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% extends 'lendborrow/base.html' %}
{% block content %}
    logged in as: {{logged_in_as}}<br>
    <form action = "/reports/" method="POST">{% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="submitted" value="Save" >
    </form>
{% endblock %}
</body>
</html>

lendborrow/templates/forms/select_record.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% extends 'lendborrow/base.html' %}
{% block content %}
<style>
    table, th, td {
        border: 1px solid black;
        font size="2";
        align="left";
    }
</style>
<h1> Select Record</h1>
{{lender}}<br>


{% if not borroweds %}
    No items are left 'open' that can be
    {% if mode = 'Edit Borrow' %}
        editted
    {% elif mode = 'Return Item' %}
        marked as returned
    {% endif %}
{% else %}

        Select an item to
        {% if mode = 'Edit Borrow' %}
            edit
        {% elif mode = 'Return Item' %}
            mark as returned
        {% endif %}
<style>
table, th, td {
    border: 1px solid black;
    font size="2";
    align="left";
}
</style>

    <table>

            <col width="20">
            <col width="130">
            <col width="130">
            <col width="100">
            <col width="500">
            <col width="100">
            <col width="100">
            <col width="100">


       <br><b> {{ error_message }}</b><br>

            <th>
                ID
            </th>
            <th>
                Borrower
            </th>
            <th>
                Borrowed Date
            </th>
            <th>
                Category
            </th>
            <th>
                Description
            </th>
            <th>
                Condition
            </th>

            <th>
                Status
            </th>
            <th>
                Expected Return Day
            </th>

            {% for b in borroweds %}
        <tr>
            <td>
                {{b.id}}
            </td>
            <td>
                {{b.borrow_transaction.borrower}}
            </td>
            <td>
                {{b.borrow_transaction.borrowed_date|date:"m\/d\/Y"}}
            </td>
            <td>
                {{b.get_item_category_display}}
            </td>
            <td>
                {{b.item_short_desc}}

            </td>
            <td>
                {{b.get_borrowed_condition_display}}
            </td>
            <td>
                {{b.borrowed_status}}
            </td>
            <td>
                {{b.expected_return_date}}
            </td>
        </tr>
        {% endfor %}

    </table>

<hr>
            <form action="/selected/" method="post">{% csrf_token %}
                item ID <input type="text" name="item_id">
                {% if mode = 'Edit Borrow' %}
                    <input type="submit" name="submitted" value="item to edit">
                {% elif mode = 'Return Item' %}
                    <input type="submit" name="submitted" value="item to return">
                {% endif %}

            </form>
        {% endif %}
{% endblock %}
</body>
</html>